apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  namespace: jenkins
spec:
  serviceAccountName: kaniko-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - '--dockerfile=Dockerfile'
        - '--context=/workspace/'
        - '--destination=docker.io/potatoj1n/gigboard-fe:latest'
        - '--verbosity=debug'
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-storage
          mountPath: /workspace/
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: dockerfile-storage
      hostPath:
        path: /home/eunjin/Frontend # 절대 경로로 설정
